### ISSUE TITLE
Continuous Voice Input for ALAN

### ISSUE THREAD

**Issue by omarhuseynov011** [omarhuseynov011/ALAN#2]
# ALAN needs to listen for voice input **continuously**

Right now ALAN listens for input for a fairly short period of time, if no input was received it stops listening.

However, ALAN should **always** listen for voice input

I believe this is related to the Google API directly

Below is the code segment that decides to cut listening

_It executes when no voice input has been detected for a specific period of time_

```
recognition.onerror = function(event){
            if(event.error === 'no-speech'){
                // ALAN could not detect speech
                // There could be a problem with microphone settings
                // Possible Solution: Adjust microphone settings
                console.log('No speech was detected');
                ignore_on_end = true;
            }
```

**Comment by omarhuseynov011** [comment]
Continuous input will be disabled for the Web version

**Comment by mert-celen** [comment]
hahaha
